name: Apply Terraform to AWS 

on: 
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

defaults:
  run:
    working-directory: ./terraform

jobs:
  fmt:
    name: Format and Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        run: terraform init

      - name: Format Terraform
        run: terraform fmt -check

      - name: Validate Terraform
        run: terraform validate


  deploy:
    needs: fmt
    name: Plan and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        run: terraform init
      
      - name: terraform plan
        run: terraform plan -out=plan.out
      
      - name: terraform apply
        run: terraform apply -auto-approve plan.out